version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gateway"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wtgwiuqxl47z"
s3_prefix = "gateway"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
