AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fact-wise


Globals:
  Function:
    Runtime: python3.8
    Architectures:
      - x86_64
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders_api/
      Handler: create.private
      Events:
        CreateGateway:
          Type: Api
          Properties:
            Path: /gateway
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
  
  ReadOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders_api/
      Handler: read.public
      Events:
        ReadGateway:
          Type: Api
          Properties:
            Path: /gateway/{id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable